name: Автоматична публікація новин

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  publish_news:
    runs-on: ubuntu-latest

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v3

      - name: Налаштування Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name:
